package orp.ardnahcimor.invidao.database.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import orp.ardnahcimor.invidao.database.model.Wig;

import orp.ardnahcimor.invidao.database.model.WigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wigDaoConfig;

    private final WigDao wigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wigDaoConfig = daoConfigMap.get(WigDao.class).clone();
        wigDaoConfig.initIdentityScope(type);

        wigDao = new WigDao(wigDaoConfig, this);

        registerDao(Wig.class, wigDao);
    }
    
    public void clear() {
        wigDaoConfig.clearIdentityScope();
    }

    public WigDao getWigDao() {
        return wigDao;
    }

}
